name:                driftwood
version:             0.1.0.0
github:              "netom/driftwood"
license:             BSD3
author:              "Tamas Laszlo Fabian"
maintainer:          "giganetom@gmail.com"
copyright:           "2019 Tamas Laszlo Fabian"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Simple leader election tool based on raft
category:            Network

description:         Please see the README on GitHub at <https://github.com/netom/driftwood#readme>

dependencies:
- async
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- mtl
- network
- optparse-applicative
- random
- split
- stm
- time
library:
  source-dirs: src

executables:
  driftwood:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - driftwood

tests:
  driftwood-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - driftwood
